MENU_BUTTON_DEFINITIONS = [
    {"name": "easy",
     "x_pos": 0.35,
     "y_pos": 0.3,
     "width": 0.3,
     "height": 0.1,
     "text" : "PLAY",
     "image": "Assets\_UIMenu\Btn.png",
     "hover_image": "Assets\_UIMenu\Hovered_Btn.png"},

    {"name": "credits",
     "x_pos": 0.35,
     "y_pos": 0.6,
     "width": 0.3,
     "height": 0.1,
     "text" : "CREDITS",
     "image": "Assets\_UIMenu\Btn.png",
     "hover_image": "Assets\_UIMenu\Hovered_Btn.png"
     },

    {"name": "weapon",
     "x_pos": 0.35,
     "y_pos": 0.45,
     "width": 0.3,
     "height": 0.1,
     "text" : "WEAPON",
     "image": "Assets\_UIMenu\Btn.png",
     "hover_image": "Assets\_UIMenu\Hovered_Btn.png"},

    {"name": "exit",
     "x_pos": 0.35,
     "y_pos": 0.75,
     "width": 0.3,
     "height": 0.1,
     "text": "EXIT",
     "image": "Assets\_UIMenu\Btn.png",
     "hover_image": "Assets\other\logo.png"},
]

MENU_WEAPON_BUTTON_DEFINITIONS = [
    {"name": "mashinegun",
     "x_pos": 0.1,
     "y_pos": 0.1,
     "width": 0.2,
     "height": 0.2,
     "text" : "",
     "image": "Assets\guns\gun3.png",
     "hover_image": "Assets\other\logo.png"},

    {"name": "rocketlauncher",
     "x_pos": 0.4,
     "y_pos": 0.1,
     "width": 0.2,
     "height": 0.2,
     "text" :"",
     "image": "Assets\guns\gun1.png",
     "hover_image": "Assets\other\logo.png"},

    {"name": "blaster",
     "x_pos": 0.7,
     "y_pos": 0.1,
     "width": 0.2,
     "height": 0.2,
     "text" : "",
     "image": "Assets\guns\gun4.png",
     "hover_image": "Assets\other\logo.png"},

     {"name": "firethrower",
     "x_pos": 0.1,
     "y_pos": 0.4,
     "width": 0.2,
     "height": 0.2,
     "text" : "",
     "image": "Assets\guns\gun5.png",
     "hover_image": "Assets\other\logo.png"},

     {"name": "lasergun",
     "x_pos": 0.4,
     "y_pos": 0.4,
     "width": 0.2,
     "height": 0.2,
     "text" : "",
     "image": "Assets\guns\gun7.png",
     "hover_image": "Assets\other\logo.png"},

    {"name": "exit",
     "x_pos": 0.35,
     "y_pos": 0.75,
     "width": 0.3,
     "height": 0.1,
     "text": "EXIT",
     "image": "Assets\_UIMenu\Btn.png",
     "hover_image": "Assets\other\logo.png"},
]

PAUSE_BUTTON_DEFINITIONS = [
    {"name": "resume",
     "y_pos": 0.4,
     "text" : "RESUME",
     "image": "Assets\_UIMenu\Btn.png",
     "hover_image": "Assets\_UIMenu\Hovered_Btn.png"},
    {"name": "main_menu",
     "y_pos": 0.55,
     "text" : "HOME",
     "image": "Assets\_UIMenu\Btn.png",
     "hover_image": "Assets\_UIMenu\Hovered_Btn.png"},
    {"name": "exit",
     "y_pos": 0.7,
     "text" : "EXIT",
     "image": "Assets\_UIMenu\Btn.png",
     "hover_image": "Assets\other\logo.png"}
]

BUFF_BUTTON_DEFINITIONS = [
    {"name": "BuffAtk",
     "x_pos": 0.35,
     "y_pos": 0.3,
     "width": 0.3,
     "height": 0.1,
     "text" : "ATTACK",
     "image": "Assets\_UIMenu\Btn.png",
     "hover_image": "Assets\_UIMenu\Hovered_Btn.png"},

    {"name": "BuffHP",
     "x_pos": 0.35,
     "y_pos": 0.45,
     "width": 0.3,
     "height": 0.1,
     "text" : "MAX HEALTH",
     "image": "Assets\_UIMenu\Btn.png",
     "hover_image": "Assets\_UIMenu\Hovered_Btn.png"},

    {"name": "BuffSPD",
     "x_pos": 0.35,
     "y_pos": 0.6,
     "width": 0.3,
     "height": 0.1,
     "text" : "SPEED",
     "image": "Assets\_UIMenu\Btn.png",
     "hover_image": "Assets\_UIMenu\Hovered_Btn.png"}
]
